In [1]:
import numpy as np 
import itertools as it
# from scipy.stats import multivariate_normal
from tqdm import tqdm

In [2]:
from scipy.stats import multivariate_normal


In [146]:
t = np.arange(0,51,0.5)

In [147]:
t

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5])

In [148]:
t = t[:-1]
t

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. ])

In [153]:
e_x = np.linspace(-3,3,10)
e_y = e_x
e_x

array([-3.        , -2.33333333, -1.66666667, -1.        , -0.33333333,
        0.33333333,  1.        ,  1.66666667,  2.33333333,  3.        ])

In [154]:
th = np.linspace(-np.pi/4, np.pi/4, 10)
th

array([-0.78539816, -0.61086524, -0.43633231, -0.26179939, -0.08726646,
        0.08726646,  0.26179939,  0.43633231,  0.61086524,  0.78539816])

In [155]:
X = list(it.product(t,e_x,e_y, th))

In [156]:
len(X)

101000

In [157]:
X[-1]

(50.0, 3.0, 3.0, 0.7853981633974483)

In [158]:
n_states = len(X)

In [159]:
state_table = {}
for i in range(n_states):
    state_table.update({X[i]:i})

In [160]:
state_table

{(0.0, -3.0, -3.0, -0.7853981633974483): 0,
 (0.0, -3.0, -3.0, -0.6108652381980153): 1,
 (0.0, -3.0, -3.0, -0.4363323129985824): 2,
 (0.0, -3.0, -3.0, -0.26179938779914946): 3,
 (0.0, -3.0, -3.0, -0.08726646259971649): 4,
 (0.0, -3.0, -3.0, 0.08726646259971649): 5,
 (0.0, -3.0, -3.0, 0.26179938779914935): 6,
 (0.0, -3.0, -3.0, 0.43633231299858233): 7,
 (0.0, -3.0, -3.0, 0.6108652381980153): 8,
 (0.0, -3.0, -3.0, 0.7853981633974483): 9,
 (0.0, -3.0, -2.3333333333333335, -0.7853981633974483): 10,
 (0.0, -3.0, -2.3333333333333335, -0.6108652381980153): 11,
 (0.0, -3.0, -2.3333333333333335, -0.4363323129985824): 12,
 (0.0, -3.0, -2.3333333333333335, -0.26179938779914946): 13,
 (0.0, -3.0, -2.3333333333333335, -0.08726646259971649): 14,
 (0.0, -3.0, -2.3333333333333335, 0.08726646259971649): 15,
 (0.0, -3.0, -2.3333333333333335, 0.26179938779914935): 16,
 (0.0, -3.0, -2.3333333333333335, 0.43633231299858233): 17,
 (0.0, -3.0, -2.3333333333333335, 0.6108652381980153): 18,
 (0.0, -3.0, -2.333

In [161]:
v = np.linspace(0,1,5)
v

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [162]:
w = np.linspace(-1,1,10)
w

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [163]:
U = list(it.product(v,w))
n_controlspace = len(U)
n_controlspace

50

In [164]:
pdf = multivariate_normal(mean=[0,0,0], cov=np.diag([0.04, 0.04, 0.004]))

In [165]:
time_step = 0.5
def lissajous(k):
    xref_start = 0
    yref_start = 0
    A = 2
    B = 2
    a = 2*np.pi/50
    b = 3*a
    T = np.round(2*np.pi/(a*time_step))
    k = k % T
    delta = np.pi/2
    xref = xref_start + A*np.sin(a*k*time_step + delta)
    yref = yref_start + B*np.sin(b*k*time_step)
    v = [A*a*np.cos(a*k*time_step + delta), B*b*np.cos(b*k*time_step)]
    thetaref = np.arctan2(v[1], v[0])
    return [xref, yref, thetaref]

traj = lissajous
cur_ref = []
for i in range(200):
    cur_ref.append(traj(i))

In [166]:
cur_ref

[[2.0, 0.0, 1.5707963267948966],
 [1.9960534568565431, 0.37476262917144926, 1.5921006921904968],
 [1.9842294026289558, 0.736249105369356, 1.6156992286938656],
 [1.9645745014573774, 1.0716535899579933, 1.6446383379468776],
 [1.9371663222572624, 1.3690942118573775, 1.6840275981159143],
 [1.9021130325903073, 1.618033988749895, 1.7442784458375737],
 [1.8595529717765027, 1.8096541049320392, 1.851389534598185],
 [1.809654104932039, 1.9371663222572622, 2.089390344185407],
 [1.7526133600877274, 1.9960534568565431, 2.768858321017985],
 [1.6886558510040304, 1.9842294026289555, -2.5297141070255216],
 [1.618033988749895, 1.902113032590307, -2.1358682644473594],
 [1.5410264855515785, 1.752613360087727, -1.9861776960387143],
 [1.4579372548428229, 1.5410264855515785, -1.914558799096802],
 [1.3690942118573777, 1.274847979497379, -1.8762851950517316],
 [1.274847979497379, 0.9635073482034304, -1.8559027523558818],
 [1.1755705045849465, 0.6180339887498942, -1.8470941498877218],
 [1.0716535899579933, 0.25

In [213]:
def error_dynamics(e, u,t, ref = cur_ref):
    '''
    : given current error, time, control, current reference and next reference
    : output -> Next error
    : Consider noise in the motion model. 
    '''
    G = np.array([[0.5 * np.cos(e[2] + ref[t][2]), 0], [0.5 * np.sin(e[2] + ref[t][2]), 0], [0, 0.5]])
    ref_diff = np.array([[ref[t][0] - ref[t+1][0]], [ref[t][1] - ref[t+1][1]], [ref[t][2] -  ref[t+1][2]]])
#     print(f'e shape : {e.shape}')
    next_error = e[:,None] + G @ np.array([[u[0]], [u[1]]]) + ref_diff
    next_error[2] = (next_error[2] + np.pi)%(2*np.pi) - np.pi
#     print(f'next error : {next_error}')
    next_x, next_y, next_th = next_error[0], next_error[1], next_error[2]
    ind_x = (next_x - e_x).argsort()[:5]
    ind_y = (next_y - e_y).argsort()[:5]
    ind_th = (next_th - th).argsort()[:5]    
    next_states, pr = [],[]
    for i in range(5):
        next_states.append(state_table[((t + 1)%50, e_x[ind_x[i]], e_y[ind_y[i]], th[ind_th[i]])])
        pr.append(pdf.pdf([e_x[ind_x[i]], e_y[ind_y[i]], th[ind_th[i]]]))
    pr = np.array(pr)
    pr /= np.sum(pr)
    print(f'probs : {pr}')
    return next_states, pr

In [168]:
def step_cost(e, u):
    '''
    : given the current error and the control
    : compute the step cost defined as the sum of tracking errors and control effort
    '''
    Q = np.eye(2)
    q = 1 
    R = np.eye(2)
    p = e[:2]
    th = e[-1]
    u = np.array([[u[0]],[u[1]]])
    return p.T @ Q @ p + q*(1 - np.cos(th))**2 + u.T @ R @ u

In [207]:
V = np.zeros(n_states)
pi = np.zeros((n_states,2))

In [222]:
def value_iteration(V,pi):
    for iter in tqdm(range(5000)):
        V_new = np.zeros_like(V)
        for state in (range(n_states)):
            temp = np.zeros(len(U))
            e = np.array(X[state][1:])
            t = int(X[state][0]//0.5)
#             print(t)
            for j,control in enumerate(U):
                next_states, pr = error_dynamics(e,control,t)
                V_next = [V[i] for i in next_states]
#                 print(f'value function at next states : {V_next}')
                temp[j] = step_cost(e, control) + 0.98 * np.sum(pr * V_next)
            V_new[state] = np.min(temp)
            pi[state] = U[np.argmin(temp)]

        diff = np.linalg.norm(V_new - V, np.inf)
        print(f'diff : {diff}')
        if diff < 2.5e-2:
            return V_new,pi
        else:
            V = V_new

In [223]:
value_iteration(V,pi)

  0%|                                       | 1/5000 [00:58<81:43:05, 58.85s/it]

diff : 0.500009502831313


  0%|                                       | 2/5000 [01:57<81:55:55, 59.01s/it]

diff : 0.03207865527641335


  0%|                                       | 3/5000 [02:57<82:06:24, 59.15s/it]

diff : 0.031437082170885144


  0%|                                       | 4/5000 [03:55<81:50:09, 58.97s/it]

diff : 0.030808340527467393


  0%|                                       | 5/5000 [04:54<81:38:52, 58.85s/it]

diff : 0.03019217371691807


  0%|                                       | 6/5000 [05:53<81:37:20, 58.84s/it]

diff : 0.029588330242579675


  0%|                                       | 7/5000 [06:52<81:37:17, 58.85s/it]

diff : 0.028996563637728068


  0%|                                       | 8/5000 [07:51<81:36:45, 58.86s/it]

diff : 0.02841663236497352


  0%|                                       | 9/5000 [08:50<81:36:26, 58.86s/it]

diff : 0.027848299717674108


  0%|                                      | 10/5000 [09:49<81:40:26, 58.92s/it]

diff : 0.0272913337233206


  0%|                                      | 11/5000 [10:47<81:35:59, 58.88s/it]

diff : 0.026745507048854145


  0%|                                      | 12/5000 [11:48<82:27:21, 59.51s/it]

diff : 0.026210596907877082


  0%|                                      | 13/5000 [12:49<82:43:14, 59.71s/it]

diff : 0.025686384969719533


  0%|                                      | 14/5000 [13:49<82:52:19, 59.84s/it]

diff : 0.02517265727032514


  0%|                                      | 14/5000 [14:48<87:56:49, 63.50s/it]

diff : 0.024669204124918576


(array([0.89515126, 0.89514236, 0.89514176, ..., 0.89514176, 0.89514236,
        0.89515126]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]]))

In [169]:
L = np.zeros((n_states,n_controlspace))
for i in tqdm(range(n_states)):
    for j in range(n_controlspace):
        e = X[i][1:]
        L[i,j] = step_cost(np.array(e), U[j])

100%|█████████████████████████████████| 101000/101000 [01:20<00:00, 1262.35it/s]


In [170]:
L.shape

(101000, 50)

In [126]:
L[5]

array([12.25239546, 11.85733374, 11.56103744, 11.36350658, 11.26474114,
       11.26474114, 11.36350658, 11.56103744, 11.85733374, 12.25239546,
       12.26474114, 11.86967942, 11.57338312, 11.37585225, 11.27708682,
       11.27708682, 11.37585225, 11.57338312, 11.86967942, 12.26474114,
       12.30177818, 11.90671645, 11.61042016, 11.41288929, 11.31412386,
       11.31412386, 11.41288929, 11.61042016, 11.90671645, 12.30177818,
       12.36350658, 11.96844485, 11.67214855, 11.47461769, 11.37585225,
       11.37585225, 11.47461769, 11.67214855, 11.96844485, 12.36350658,
       12.44992633, 12.0548646 , 11.7585683 , 11.56103744, 11.46227201,
       11.46227201, 11.56103744, 11.7585683 , 12.0548646 , 12.44992633,
       12.56103744, 12.16597571, 11.86967942, 11.67214855, 11.57338312,
       11.57338312, 11.67214855, 11.86967942, 12.16597571, 12.56103744,
       12.69683991, 12.30177818, 12.00548188, 11.80795102, 11.70918559,
       11.70918559, 11.80795102, 12.00548188, 12.30177818, 12.69

In [216]:
from scipy.sparse import csr_matrix
P =[]
for i in tqdm(range(5)):
    e = np.array(X[i][1:])
    t = int(X[i][0]//0.5)
    p = np.zeros((n_controlspace, n_states))
    for j in range(n_controlspace):
        next_states, pr = error_dynamics(e,U[j],t)
#         print(f'probs : {pr}')
        for k in range(len(next_states)):
            p[j,next_states[k]] = pr[k]
    print(f'sum probs : {np.sum(p, axis = 1)}')
    P.append(csr_matrix(p))
P = np.array(P)

 40%|██████████████████                           | 2/5 [00:00<00:00, 18.93it/s]

probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]

100%|█████████████████████████████████████████████| 5/5 [00:00<00:00, 18.56it/s]

probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]
probs : [2.61035159e-130 1.77835886e-078 1.33355122e-039 1.10070237e-013
 1.00000000e+000]

In [210]:
P

array([<50x101000 sparse matrix of type '<class 'numpy.float64'>'
       	with 250 stored elements in Compressed Sparse Row format>,
       <50x101000 sparse matrix of type '<class 'numpy.float64'>'
       	with 250 stored elements in Compressed Sparse Row format>,
       <50x101000 sparse matrix of type '<class 'numpy.float64'>'
       	with 250 stored elements in Compressed Sparse Row format>,
       <50x101000 sparse matrix of type '<class 'numpy.float64'>'
       	with 250 stored elements in Compressed Sparse Row format>,
       <50x101000 sparse matrix of type '<class 'numpy.float64'>'
       	with 250 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [211]:
P[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [196]:
P.shape

(101000,)

In [197]:
P.nbytes

808000

In [199]:
x = P[0].toarray()

In [200]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [201]:
np.sum(x[0])

4.99999999999945

In [217]:
def value_iteration_matrix(V,pi,L,P):
    for i in tqdm(range(5000)):
        V_new = np.zeros_like(V)
        Q = L + 0.98 * np.sum(P @ V, axis = 2)
        V_new = np.min(Q, axis = 1, keepdims=True)
#         print(f'shape V_new : {V_new.shape}')
        pi = np.argmin(Q, axis = 1)
        diff = np.linalg.norm(V_new - V, np.inf)
        print(f'diff : {diff}')
        if diff < 0.03 : 
            return V_new, pi
        else:
            V = V_new

In [218]:
V = np.zeros((n_states, 1))
pi = np.zeros((n_states,2))
V_opt, pi_opt = value_iteration_matrix(V,pi,L,P)

  0%|                                                  | 0/5000 [00:00<?, ?it/s]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 101000 is different from 5)

In [133]:
pi_opt

array([4, 4, 4, ..., 4, 4, 4])

In [134]:
pi_opt[5000:5020]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [135]:
np.bincount(pi_opt)

array([    0,     0,     0,     0, 12625])

In [142]:
from time import time
import numpy as np
from utils import visualize
# Simulation params
np.random.seed(10)
time_step = 0.5 # time between steps in seconds
sim_time = 120    # simulation time

# Car params
x_init = 1.5
y_init = 0.0
theta_init = np.pi/2
v_max = 1
v_min = 0
w_max = 1
w_min = -1

# This function implement the car dynamics
def car_next_state(time_step, cur_state, control, noise = True):
    theta = cur_state[2]
    rot_3d_z = np.array([[np.cos(theta), 0], [np.sin(theta), 0], [0, 1]])
    f = rot_3d_z @ control
    mu, sigma = 0, 0.04 # mean and standard deviation for (x,y)
    w_xy = np.random.normal(mu, sigma, 2)
    mu, sigma = 0, 0.004  # mean and standard deviation for theta
    w_theta = np.random.normal(mu, sigma, 1)
    w = np.concatenate((w_xy, w_theta))
    if noise:
        return cur_state + time_step*f.flatten() + w
    else:
        return cur_state + time_step*f.flatten()

# Obstacles in the environment
obstacles = np.array([[-2,-2,0.5], [1,2,0.5]])
# Params
traj = lissajous
ref_traj = []
error = 0.0
car_states = []
times = []
# Start main loop
main_loop = time()  # return time in sec
# Initialize state
cur_state = np.array([x_init, y_init, theta_init])
cur_iter = 0
# Main loop
while (cur_iter * time_step < sim_time):
    t1 = time()
    # Get reference state
    cur_time = cur_iter*time_step
    # cur_ref = traj(cur_iter)
    cur_ref = []
    for i in range(120):
        cur_ref.append(traj(cur_iter + i))
    # Save current state and reference state for visualization
    ref_traj.append(cur_ref[0])
    car_states.append(cur_state)

    ################################################################
    # Generate control input
    # TODO: Replace this simple controller with your own controller
    # control = simple_controller(cur_state, cur_ref)
#     control = casadi_controller(cur_state, cur_ref)
    error = cur_state - cur_ref[0]
    error[2] = (error[2] + np.pi) %(2*np.pi) - np.pi
    error_x, error_y, error_th = error[0], error[1], error[2]
    ind_x = (error_x - e_x).argsort()[0]
    ind_y = (error_y - e_y).argsort()[0]
    ind_th = (error_th - th).argsort()[0]
    error = list([e_x[ind_x], e_y[ind_y], th[ind_th]])
    print(f'error : {error}')
    control = U[pi_opt[state_table[(cur_iter * time_step % 50,error[0], error[1], error[2])]]]
    v = control[0]
    w = control[1]
    v = np.clip(v, v_min, v_max)
    w = np.clip(w,w_min, w_max)
    print("[v,w]", control)
    ################################################################

    # Apply control input
    next_state = car_next_state(time_step, cur_state, control, noise=True)
    # Update current state
    cur_state = next_state
    # Loop time
    t2 = time()
    print(cur_iter)
    print(t2-t1)
    times.append(t2-t1)
    error = error + np.linalg.norm(cur_state - cur_ref)
    cur_iter = cur_iter + 1

main_loop_time = time()
print('\n\n')
print('Total time: ', main_loop_time - main_loop)
print('Average iteration time: ', np.array(times).mean() * 1000, 'ms')
print('Final error: ', error)

# Visualization
ref_traj = np.array(ref_traj)
car_states = np.array(car_states)
times = np.array(times)
visualize(car_states, ref_traj, obstacles, times, time_step, save=True)

error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
0
0.0024123191833496094
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
1
0.0021996498107910156
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
2
0.0022225379943847656
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
3
0.006588935852050781
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
4
0.0035316944122314453
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
5
0.0034809112548828125
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
6
0.0034863948822021484
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
7
0.0034623146057128906
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
8
0.003366231918334961
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
9
0.0023751258850097656
error : [3.0, 3.0, 0.31415926535

121
0.001967191696166992
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
122
0.0017740726470947266
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
123
0.0017702579498291016
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
124
0.0017573833465576172
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
125
0.001760721206665039
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
126
0.0017349720001220703
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
127
0.0017459392547607422
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
128
0.001728057861328125
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
129
0.001729726791381836
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
130
0.00176239013671875
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
131
0.0017557144

227
0.001973390579223633
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
228
0.0018057823181152344
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
229
0.0017726421356201172
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
230
0.0017778873443603516
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
231
0.0017621517181396484
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
232
0.0017573833465576172
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
233
0.001764059066772461
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
234
0.0018694400787353516
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
235
0.0017347335815429688
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
236
0.0017712116241455078
error : [3.0, 3.0, 0.3141592653589793]
[v,w] (0.0, -0.11111111111111116)
237
0.001743

MovieWriter ffmpeg unavailable; using Pillow instead.


In [172]:
from scipy.sparse import csr_matrix
a = np.array([[1,1,0,0,0], [0,1,2,0,0]])

In [173]:
S = csr_matrix(a)

In [174]:
S

<2x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [175]:
S.sum(axis = 1)

matrix([[2],
        [3]])

In [176]:
b = np.array([[1,1,1,1,1]])
b.shape

(1, 5)

In [177]:
b = b.T

In [178]:
b.shape

(5, 1)

In [179]:
S.shape

(2, 5)

In [180]:
S @ b

array([[2],
       [3]])

In [185]:
a = []

In [186]:
a.append(S)

In [188]:
a.append(S)

In [189]:
a

[<2x5 sparse matrix of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Row format>,
 <2x5 sparse matrix of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Row format>]

In [190]:
a[0]

<2x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [191]:
a = np.array(a)

In [192]:
a

array([<2x5 sparse matrix of type '<class 'numpy.int64'>'
       	with 4 stored elements in Compressed Sparse Row format>,
       <2x5 sparse matrix of type '<class 'numpy.int64'>'
       	with 4 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [193]:
a.nbytes

16

In [206]:
a = np.array([1,2,3,4])
np.sum(a)
type(_)
type(a)

numpy.ndarray

In [207]:
a = a / 10.0

In [208]:
a

array([0.1, 0.2, 0.3, 0.4])